name: fang2022
channels:
  - defaults
dependencies:
  - astroid=2.6.6
  - ca-certificates=2021.10.26
  - certifi=2020.12.5
  - isort=5.9.3
  - lazy-object-proxy=1.6.0
  - libcxx=12.0.0
  - libedit=3.1.20210910
  - libffi=3.3
  - mccabe=0.6.1
  - ncurses=6.3
  - openssl=1.1.1m
  - pip=21.2.2
  - pylint=2.9.6
  - python=3.6.13
  - readline=8.1.2
  - rope=0.21.1
  - setuptools=58.0.4
  - six=1.16.0
  - sqlite=3.37.0
  - tk=8.6.11
  - toml=0.10.2
  - typed-ast=1.4.3
  - typing_extensions=3.10.0.2
  - wheel=0.37.1
  - wrapt=1.12.1
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - aggdraw==1.3.12
    - anyio==2.2.0
    - appnope==0.1.2
    - argon2-cffi==20.1.0
    - async-generator==1.10
    - attrs==20.3.0
    - backcall==0.2.0
    - bleach==3.3.0
    - cffi==1.14.5
    - chardet==4.0.0
    - click==7.1.2
    - colorama==0.4.4
    - configparser==5.2.0
    - contextvars==2.4
    - cycler==0.10.0
    - dataclasses==0.8
    - decorator==4.4.2
    - defusedxml==0.6.0
    - deprecation==2.1.0
    - docker-pycreds==0.4.0
    - entrypoints==0.3
    - future==0.18.2
    - gitdb==4.0.7
    - gitpython==3.1.14
    - idna==2.10
    - immutables==0.15
    - importlib-metadata==3.5.0
    - ipykernel==5.5.0
    - ipython==7.16.1
    - ipython-genutils==0.2.0
    - ipywidgets==7.6.3
    - jinja2==2.11.3
    - joblib==1.0.1
    - jsonschema==3.2.0
    - jupyter==1.0.0
    - jupyter-client==6.1.11
    - jupyter-console==6.2.0
    - jupyter-core==4.7.1
    - jupyter-packaging==0.9.2
    - jupyter-server==1.6.4
    - jupyter-server-mathjax==0.2.2
    - jupyterlab-pygments==0.1.2
    - jupyterlab-widgets==1.0.0
    - kaleido==0.2.1
    - kiwisolver==1.3.1
    - markupsafe==1.1.1
    - matplotlib==3.3.4
    - mistune==0.8.4
    - nbclient==0.5.2
    - nbconvert==6.0.7
    - nbdime==3.0.0
    - nbformat==5.1.2
    - nest-asyncio==1.5.1
    - nltk==3.6.2
    - notebook==6.2.0
    - numpy==1.19.5
    - packaging==20.9
    - pandas==1.1.5
    - pandocfilters==1.4.3
    - parso==0.8.1
    - pathtools==0.1.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==8.1.0
    - plotly==5.5.0
    - prometheus-client==0.9.0
    - promise==2.3
    - prompt-toolkit==3.0.16
    - protobuf==3.19.1
    - psutil==5.8.0
    - ptyprocess==0.7.0
    - pycparser==2.20
    - pygments==2.8.0
    - pyparsing==2.4.7
    - pyrsistent==0.17.3
    - python-dateutil==2.8.1
    - pytz==2021.1
    - pyyaml==5.4.1
    - pyzmq==22.0.3
    - qtconsole==5.0.2
    - qtpy==1.9.0
    - regex==2021.4.4
    - requests==2.25.1
    - scikit-learn==0.24.2
    - scipy==1.5.4
    - seaborn==0.11.1
    - send2trash==1.5.0
    - sentry-sdk==1.5.1
    - shapely==1.7.1
    - shortuuid==1.0.8
    - sklearn==0.0
    - smmap==4.0.0
    - sniffio==1.2.0
    - subprocess32==3.5.4
    - tenacity==8.0.1
    - termcolor==1.1.0
    - terminado==0.9.2
    - testpath==0.4.4
    - threadpoolctl==2.1.0
    - tomlkit==0.7.0
    - torch==1.2.0
    - torchsummary==1.5.1
    - torchvision==0.4.0
    - tornado==6.1
    - tqdm==4.57.0
    - traitlets==4.3.3
    - typing-extensions==3.7.4.3
    - urllib3==1.26.4
    - wandb==0.12.9
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - widgetsnbextension==3.5.1
    - yapf==0.31.0
    - yaspin==2.1.0
    - zipp==3.4.0